name: Build and Deploy Docs

on:
  push:
    branches: [ master, dev ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y doxygen graphviz
          sudo apt install -y texlive-latex-base texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended texlive-xetex

      - name: Build documentation
        run: |
          doxygen Doxyfile

          # Move HTML output
          if [ "${{ github.ref_name }}" = "master" ]; then
            mv doxygen-doc/html site-master
          else
            mv doxygen-doc/html site-dev
          fi

          # Buiĺd PDF
          cd doxygen-doc/latex
          make
          cd ../..

          # Move PDF
          if [ "${{ github.ref_name }}" = "master" ]; then
            mkdir -p site-master/pdf
            mv doxygen-doc/latex/refman.pdf site-master/pdf/yahelpers.pdf
          else
            mkdir -p site-dev/pdf
            mv doxygen-doc/latex/refman.pdf site-dev/pdf/yahelpers.pdf
          fi

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ github.ref_name == 'master' && 'site-master' || 'site-dev' }}


  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
